# Build documentation
name: Attempt to Build Documentation

defaults:
  run:
    shell: bash

on: [push, pull_request]  # Runs on all push events to any branch

jobs:
  documentation:
    name: ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:  # only lowest supported Python on latest ubuntu
        os: [ubuntu-latest]
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Install LaTeX
        run: sudo apt-get install -y texlive-latex-base # texlive-fonts-extra texlive-fonts-recommended texlive-latex-extra texlive-latex-recommended ghostscript

      - name: Install optipng
        run: sudo apt-get install -y optipng

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Get full Python version
        id: full-python-version
        run: echo ::set-output name=version::$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))")

      - name: Set up cache
        uses: actions/cache@v2
        id: cache
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Ensure cache is healthy
        if: steps.cache.outputs.cache-hit == 'true'
        run: pip --version >/dev/null 2>&1 || rm -rf .venv

      - name: Upgrade pip, setuptools and wheel
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Install package
        run: pip install '.[docs]'

      - name: Build documentation
        run: python -m sphinx -b html docs doc_build -d doc_build

      - name: Upload build artifacts  # upload artifacts so PR reviewers can have a quick look without building the branch locally
        uses: actions/upload-artifact@v2
        if: success() && github.event_name == 'pull_request'
        with:
          name: site-build
          path: doc_build
          retention-days: 5
